# Generated by Django 2.1.5 on 2020-09-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0012_auto_20200909_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench_cells', to='matrices.Matrix'),
        ),
    ]
