# Generated by Django 3.1.2 on 2021-01-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0016_collection_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisation',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorisations', to='matrices.matrix', verbose_name='Bench'),
        ),
    ]
