# Generated by Django 3.1.2 on 2021-01-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0018_auto_20210126_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(to='matrices.Image'),
        ),
    ]
