# Generated by Django 3.1.2 on 2021-02-04 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0019_auto_20210127_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(related_name='collections', to='matrices.Image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
