# Generated by Django 3.1.2 on 2021-02-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0020_auto_20210204_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
    ]
