# Generated by Django 3.1.2 on 2021-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0022_auto_20210217_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_id', models.IntegerField(default=0)),
                ('matrix_title', models.CharField(default='', max_length=255)),
                ('matrix_description', models.TextField(default='', max_length=4095)),
                ('matrix_blogpost', models.CharField(blank=True, default='', max_length=50)),
                ('matrix_created', models.DateTimeField()),
                ('matrix_modified', models.DateTimeField()),
                ('matrix_height', models.IntegerField(default=0)),
                ('matrix_width', models.IntegerField(default=0)),
                ('matrix_owner', models.CharField(default='', max_length=50)),
                ('matrix_authorisation_id', models.IntegerField(default=0)),
                ('matrix_authorisation_permitted', models.CharField(default='', max_length=50)),
                ('matrix_authorisation_authority', models.CharField(default='', max_length=12)),
            ],
            options={
                'db_table': 'matrices_bench_summary',
                'managed': False,
            },
        ),
    ]
