# Generated by Django 3.1.14 on 2022-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0024_auto_20211102_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
    ]
