# Generated by Django 3.2.16 on 2023-02-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0042_auto_20230216_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('web_root', models.CharField(default='', max_length=255)),
                ('document_root', models.CharField(default='', max_length=255)),
                ('wordpress_web_root', models.CharField(default='', max_length=255)),
                ('from_email', models.CharField(default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='environments', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='environments', to='matrices.protocol')),
            ],
        ),
    ]
