# Generated by Django 3.2.16 on 2023-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0046_remove_blog_url_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.IntegerField(default=0)),
                ('environment_name', models.CharField(max_length=50, unique=True)),
                ('environment_location', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'matrices_environment_summary',
                'managed': False,
            },
        ),
    ]
