# Generated by Django 3.2.18 on 2023-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0049_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='date_format',
            field=models.CharField(default='%A, %B %e, %Y', max_length=255),
        ),
    ]
