# Generated by Django 4.2.4 on 2023-08-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('matrices', '0050_environment_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='last_used_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lastused_tags', to='taggit.tag'),
        ),
    ]
