# Generated by Django 4.2.4 on 2023-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0051_matrix_last_used_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='nginx_private_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
