# Generated by Django 4.2.4 on 2023-10-13 08:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0052_environment_nginx_private_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='matrices_im_search__d81d1c_gin'),
        ),
    ]
