# Generated by Django 4.2.4 on 2023-10-13 13:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0054_search_vector_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='matrices_co_search__d594d8_gin'),
        ),
    ]
