# Generated by Django 4.2.4 on 2023-11-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0056_search_vector_trigger_collection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='matrices_co_search__d594d8_gin',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='matrices_im_search__d81d1c_gin',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='image',
            name='search_vector',
        ),
    ]
