# Generated by Django 4.2.4 on 2024-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0057_remove_collection_matrices_co_search__d594d8_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='wordpress_active',
            field=models.BooleanField(default=False),
        ),
    ]
