# Generated by Django 4.2.4 on 2024-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0058_environment_wordpress_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='colour',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
    ]
