# Generated by Django 4.2.4 on 2024-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0061_environment_gateway_environment_gateway_pagination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
