# Generated by Django 4.2.4 on 2024-06-27 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0062_matrix_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixPublicSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_public_id', models.IntegerField(default=0)),
                ('matrix_public_title', models.CharField(default='', max_length=255)),
                ('matrix_public_description', models.TextField(default='', max_length=4095)),
                ('matrix_public_blogpost', models.CharField(blank=True, default='', max_length=50)),
                ('matrix_public_created', models.DateTimeField()),
                ('matrix_public_modified', models.DateTimeField()),
                ('matrix_public_height', models.IntegerField(default=0)),
                ('matrix_public_width', models.IntegerField(default=0)),
                ('matrix_public_owner', models.CharField(default='', max_length=50)),
                ('matrix_public_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'matrices_bench_public_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionImageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionimageorders', to='matrices.collection')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionimageorders', to='matrices.image')),
                ('permitted', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectionimageorders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
