# Generated by Django 4.2.4 on 2024-07-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0063_matrixpublicsummary_collectionimageorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionimageorder',
            old_name='order',
            new_name='ordering',
        ),
    ]
