# Generated by Django 4.2.4 on 2024-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0065_cell_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
