# Generated by Django 4.2.4 on 2024-10-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0066_matrix_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='background_processing',
            field=models.BooleanField(default=False),
        ),
    ]
