# Generated by Django 4.2.4 on 2024-11-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0067_environment_background_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='broker_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='environment',
            name='task_pause_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='environment',
            name='window_refresh_time',
            field=models.IntegerField(default=10),
        ),
    ]
