# Generated by Django 4.2.4 on 2024-11-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0068_environment_broker_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='broker_location',
        ),
    ]
