# Generated by Django 3.1 on 2020-08-26 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisation',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorityauthorisations', to='matrices.authority'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorisations', to='matrices.matrix'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='permitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userauthorisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authority',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userauthorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userblogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='protocol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='protocolblogs', to='matrices.protocol'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagecells', to='matrices.image'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrixcells', to='matrices.matrix'),
        ),
        migrations.AlterField(
            model_name='command',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usercommands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='typecommands', to='matrices.type'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usercredentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userimages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='serverimages', to='matrices.server'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usermatrices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userprotocols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userservers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='typeservers', to='matrices.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usertypes', to=settings.AUTH_USER_MODEL),
        ),
    ]
