# Generated by Django 3.1 on 2020-08-26 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrices', '0003_auto_20200826_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisation',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorisations', to='matrices.authority'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorisations', to='matrices.matrix'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='permitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authority',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='protocol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='matrices.protocol'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='matrices.image'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='matrices.matrix'),
        ),
        migrations.AlterField(
            model_name='command',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='matrices.type'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='matrices.server'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matrices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protocols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='matrices.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to=settings.AUTH_USER_MODEL),
        ),
    ]
