# Generated by Django 2.1.5 on 2020-09-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0007_auto_20200908_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='matrices.Image'),
        ),
    ]
