# Generated by Django 3.1.2 on 2021-01-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0015_auto_20210122_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
