# Generated by Django 3.1.7 on 2021-11-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0023_matrixsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField(default=0)),
                ('collection_title', models.CharField(default='', max_length=255)),
                ('collection_description', models.TextField(default='', max_length=4095)),
                ('collection_owner', models.CharField(default='', max_length=50)),
                ('collection_active', models.BooleanField(default=True)),
                ('collection_image_count', models.IntegerField(default=0)),
                ('collection_authorisation_id', models.IntegerField(default=0)),
                ('collection_authorisation_permitted', models.CharField(default='', max_length=50)),
                ('collection_authorisation_authority', models.CharField(default='', max_length=12)),
            ],
            options={
                'db_table': 'matrices_collection_summary',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='matrices.image'),
        ),
    ]
