# Generated by Django 3.2.13 on 2022-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0026_auto_20220628_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='description',
            field=models.TextField(default='', max_length=4095),
        ),
        migrations.AlterField(
            model_name='cell',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
