# Generated by Django 3.2.15 on 2022-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0032_auto_20220826_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
