# Generated by Django 3.2.15 on 2022-09-01 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0033_artefact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='location',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'svg'])]),
        ),
    ]
