# Generated by Django 3.2.15 on 2022-10-13 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0035_alter_artefact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'svg', 'html'])]),
        ),
    ]
