# Generated by Django 3.2.15 on 2022-11-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0039_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_collections', to='matrices.collection'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_used_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lastused_collections', to='matrices.collection'),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
