# Generated by Django 3.2.16 on 2023-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0044_environment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='maximum_bench_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_cell_height',
            field=models.IntegerField(default=450),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_cell_width',
            field=models.IntegerField(default=450),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_collection_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_initial_columns',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_initial_rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_rest_columns',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='environment',
            name='maximum_rest_rows',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='environment',
            name='minimum_cell_height',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='environment',
            name='minimum_cell_width',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='environment',
            name='minimum_initial_columns',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='environment',
            name='minimum_initial_rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='environment',
            name='minimum_rest_columns',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='environment',
            name='minimum_rest_rows',
            field=models.IntegerField(default=3),
        ),
    ]
