# Generated by Django 3.2.16 on 2023-03-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0045_auto_20230228_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url_blog',
        ),
    ]
