# Generated by Django 3.2.16 on 2023-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0047_environmentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(default=0)),
                ('image_identifier', models.IntegerField(default=0)),
                ('image_name', models.CharField(default='', max_length=255)),
                ('image_viewer_url', models.CharField(default='', max_length=255)),
                ('image_birdseye_url', models.CharField(default='', max_length=255)),
                ('image_server', models.CharField(default='', max_length=50)),
                ('image_roi', models.IntegerField(default=0)),
                ('image_comment', models.TextField(default='', max_length=4095)),
                ('image_hidden', models.BooleanField(default=False)),
                ('image_owner', models.CharField(default='', max_length=50)),
                ('image_collection_id', models.IntegerField(default=0)),
                ('image_matrix_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'matrices_image_summary',
                'managed': False,
            },
        ),
    ]
