# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.TextField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.TextField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.TextField(blank=True, max_length=12, unique=True),
        ),
    ]
