# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181108_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
