# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181115_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
