# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181115_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='pwd',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='server',
            name='uid',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
