# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181115_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
