# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181115_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='birdseye_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='viewer_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
