# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181119_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
