# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
    ]
