# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181119_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cell',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cell'),
        ),
    ]
