# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-11 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_auto_20181203_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(default='', max_length=50)),
                ('application', models.CharField(blank=True, default='', max_length=25)),
                ('preamble', models.CharField(blank=True, default='', max_length=50)),
                ('postamble', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Protocol')),
            ],
        ),
    ]
