# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_matrix_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='blogpost',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
