# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cell_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='apppwd',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
