# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181213_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='roi',
            field=models.IntegerField(default=0),
        ),
    ]
