# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_image_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrix',
            name='height',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='matrix',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matrix',
            name='width',
            field=models.IntegerField(default=75),
        ),
    ]
